### ISSUE TITLE
Requesting golinks at CMS 

### ISSUE THREAD

**Issue by aayatsali** [DSACMS/ospo-guide#17]
Jon Booth shared the following on slack on how to request golinks. 

Step1: compile all the links we would want to be golinks and go through the process below 

CMS has [go.cms.gov](http://go.cms.gov/), [go.medicare.gov](http://go.medicare.gov/), and [go.hc.gov](http://go.hc.gov/) shorteners. New short links can be requested through our web help desk at: https://jira.cms.gov/servicedesk/customer/portal/1/ or by email: [CMSWebHelpDesk@cms.hhs.gov](mailto:CMSWebHelpDesk@cms.hhs.gov)

**Comment by natalialuzuriaga** [comment]
Done, go.cms.gov/ospo
