### ISSUE TITLE
Archiving Repos

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/ospo-guide#9]
## Issue Report

Create guidance for when to consider publicly archiving a repository.

### Expected behavior
We are lacking a list of criteria for when a repository should be considered for archival as part of our regular reviews of the ecosystem of DSACMS (and broadly CMS Open Source) projects.

### Actual behavior
Let's do so research, find some examples of best practices from other government agencies, as well as private sector best practices, and draft a candidate process!

**Comment by natalialuzuriaga** [comment]
10/30:
Archiving repositories document has been completed. Ready to ship to ospo-guide in markdown.
Let's name the file: `archiving-repositories.md`

**Comment by sachin-panayil** [comment]
10/31:
- doc has been converted to markdown: https://drive.google.com/drive/folders/1ra6dvCeDsJTeqBO2u8AXu_qkxxP2BLHs?usp=drive_link

**Comment by sachin-panayil** [comment]
11/12:
- I think this can be closed! Double checking with Nat @natalialuzuriaga

**Comment by natalialuzuriaga** [comment]
Yup, all completed now:
- https://github.com/DSACMS/ospo-guide/pull/36
- https://github.com/DSACMS/ospo-guide/pull/34
